### ISSUE TITLE
[Bug] CORS 未做跨源处理

### ISSUE THREAD

**Issue by gdm257** [lixin59/omsUI#11]
## Related

#10 同样的问题

## Problem

反代为 HTTPS 之后，oms 前端许多功能无法使用

## Reproduce

1. 使用任意反代如 Nginx 对 oms 进行代理，并开启 SSL
2. 浏览器中通过 HTTPS 访问 oms
3. F12 开发者工具 - 网络
4. 刷新页面
5. 网络面板中能看见许多 xhr 请求被浏览器拦截，状态显示为 `(blocked:mixed-content)`

## Reason

- [src/api/http/requestUrl.ts](https://github.com/lixin59/omsUI/blob/master/src/api/http/requestUrl.ts) 中的 `baseUrl` 写死成了 `http` 协议
- 根据浏览器的同源政策（same-origin policy），必须要 `protocol` `host` `port` 全部相同才算同源
- 此时，浏览器与反代之间用的是 `https`，而 js 中的 xhr(axios) 用的是 `http`，`protocol` 不同，算是跨源
- 浏览器默认会拦截 js 脚本的跨源请求，导致前端 js 无法正常工作

## Solution

对于可能的解决方案，`protocol` 不要硬编码，而是跟随浏览器。

```js
let protocol = window.location.protocol;
export const baseUrl = `${protocol}//${localhost}/api/v1`;
```

**Comment by ssbeatty** [comment]
fix 8a9c20d8d86bbd505a873588c59830c82d9c1f81
